import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script'; // 👈 обязательно
import BottomNav from './components/BottomNav';
import LayoutInit from './LayoutInit';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
  
  <head>
        {/* ✅ Подключаем Telegram WebApp SDK корректно */}
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
          data-auth-data={process.env.NEXT_PUBLIC_TG_BOT_AUTH_DATA}
        />
      </head>
      <body className={inter.className}>
        <div style={{ width: '100vw', height: '100vh', overflow: 'auto' }}>
          {children}
          <LayoutInit /> {/* Запуск загрузки избранного */}
          <BottomNav />
        </div>
      </body>
    </html>
  );
}

